display_url: https://www.triceratops.show
logo_url: https://www.triceratops.show/img/logo-400px.png

public_folder: /episodios
media_folder: static/episodios

locale: 'pt'

collections:
  - name: 'episodios'
    label: 'Episódios'
    label_singular: 'Episódio'
    summary: '#{{episode}} {{title}}'
    folder: 'content/episodios'
    slug: '{{episode}}'
    create: true
    delete: false
    sortable_fields: ['episode', 'publishDate']
    fields:
      - { label: 'Episódio', hint: 'número do episódio', name: 'episode', widget: 'number', required: false }
      - { label: 'foo', name: 'foo', widget: 'foo', required: false }
      - { label: 'Título', name: 'title', widget: 'string', required: false }
      - { label: 'Capa', name: 'image', widget: 'image', required: false }
      - { label: 'Descrição', name: 'description', widget: 'text', required: false }
      - { label: 'Artistas tocados', hint: 'separados por vírgula', name: 'artistas', widget: 'list', required: false }
      - { label: 'Participações', hint: 'separadas por vírgula', name: 'participacoes', widget: 'list', required: false }
      - { label: 'Arquivo', name: 'podcast_file', widget: 'string', required: false }
      - { label: 'Duração', hint: 'no formato hh:mm:ss', name: 'podcast_duration', widget: 'string', required: false }
      - { label: 'Tamanho', hint: 'em bytes', name: 'podcast_bytes', widget: 'string', required: false }
      - { label: 'YouTube', name: 'youtube', widget: 'string', required: false }
      - { label: 'Publicado', name: 'published', widget: 'boolean', default: false }
      - { label: 'Data de publicação', name: 'publishDate', widget: 'datetime', required: false }
      - label: 'Corpo'
        name: 'body'
        widget: 'markdown'
        required: false
        default: |
          ## tocamos
          * {banda} - {música}

          ## participaram
          * {alguém que mandou um alô}

          ## recomendamos
          * {algum filme} (*tradução*) (ano), filme massa de fulano

          ## mencionados
          * {algum namedropping}

          ## escusas
          * {alguma merda que falamos}

          ## otras cositas más
          * [playlists com as músicas do podcast](https://www.triceratops.show/playlists/)
          * [instagram](https://www.instagram.com/triceratops.show/)
          * [twitter](https://twitter.com/TriceratopsShow/)
          * nosso email de contato é `contato@triceratops.show`

  - name: 'participacoes'
    label: 'Participações'
    label_singular: 'Participação'
    folder: 'content/participacoes'
    nested:
      depth: 2
    meta:
      path:
        label: 'Path'
        hint: 'nome da pasta/arquivo, mantenha acentos, ex.: laís-marinoni'
        widget: string
        index_file: '_index'
    create: true
    delete: false
    editor:
      preview: false
    fields:
      - { label: 'Nome', name: 'title', widget: 'string', required: false }
      - label: 'Tagline'
        hint: 'ex.: "melhor jogador de snooker de todos os tempos"'
        name: 'tagline'
        widget: 'string'
        required: false
      - { label: 'Corpo', name: 'body', widget: 'markdown', required: false }

  - name: 'artistas'
    label: 'Artistas'
    label_singular: 'Artista'
    folder: 'content/artistas'
    nested:
      depth: 2
    meta:
      path:
        label: 'Path'
        hint: 'nome da pasta/arquivo, mantenha acentos, ex.: polímeros-semicondutores'
        widget: string
        index_file: '_index'
    create: true
    delete: false
    editor:
      preview: false
    fields:
      - { label: 'Nome', name: 'title', widget: 'string', required: false }
      - { label: 'Corpo', name: 'body', widget: 'markdown', required: false }

  - name: "about"
    label: "Sobre"
    create: true
    delete: false
    editor:
      preview: false
    files:
      - name: "about-index"
        label: "Sobre"
        file: "content/sobre/_index.md"
        fields:
          - { label: Título, name: title, widget: string, required: false }
          - { label: Descrição, name: description, widget: string, required: false }
          - { label: 'Corpo', name: 'body', widget: 'markdown', required: false }
